# Generated by Django 5.1 on 2024-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
