# Generated by Django 5.1 on 2024-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=650)),
                ('src', models.CharField(max_length=150)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
