# Generated by Django 5.1 on 2024-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.CharField(default='زمان پخت: ۶۰ دقیقه', max_length=150),
        ),
    ]
