# Generated by Django 5.1 on 2024-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
    ]
